### ISSUE TITLE
<style> tag support

### ISSUE THREAD

**Issue by fehmi** [csstools/postcss-language#6]
Description says it is supported but I can't get it to work.

![image](https://user-images.githubusercontent.com/1026084/103295008-bf4c4e00-49fb-11eb-9e14-49b803bce35a.png)

**Comment by mustofa-id** [comment]
Same problem here.

**Comment by davbtmx** [comment]
Had the same problem and solved it thanks to #7 .

The reason is that my `<style>` block is in a `.vue` file and that _PostCSS Language Support_ only applies to `.css`, `.pcss`and `.postcss` files by default.

So, I had to associate the extension of the Vue component files to PostCSS in `settings.json`:
```json
{
  "files.associations": {
    "*.vue": "postcss"
  }
}
```

**Comment by davbtmx** [comment]
Using `<style lang="postcss">` it worked for me.

**Comment by marblewraith** [comment]
It's specifically the Volar extension, Vetur is more consistent. Notice the difference between `main.pcss` and the postcss embedded in the `.vue` file.

### Volar
![volar](https://user-images.githubusercontent.com/45786628/114841714-7d64dd80-9e1b-11eb-9d24-c7440d94c19d.PNG)

### Vetur
![vetur](https://user-images.githubusercontent.com/45786628/114841750-89509f80-9e1b-11eb-98a9-9f4eab51681a.PNG)

The author of Volar is aware of this, and referenced a completely different extension, `language-postcss` (see "Note" in the marketplace link):

- https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar
- https://github.com/johnsoncodehk/volar/issues/103

The downside of language-postcss is, it does not support "Syntactical Looseness" as this one does.

**Comment by fehmi** [comment]
I made a feature request about it in VS Code repo.

https://github.com/microsoft/vscode/issues/113696
